name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jcbhmr/setup-cargo-component@v1
    - uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip1
          components: rustfmt, clippy

    - run: cargo component build

    - name: Build
      run: cargo build --verbose
